version: '3.8'

services:
  backend:
    image: sairaj312005/pulsecheck-backend:${IMAGE_TAG:-latest}
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - db-data:/usr/src/app/data
    environment:
      - PORT=4000
      - DB_PATH=data/pulsecheck.db
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      
  frontend:
    image: sairaj312005/pulsecheck-frontend:${IMAGE_TAG:-latest}
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  db-data:
